package com.barryburgle.gameapp.ui.input.state

import com.barryburgle.gameapp.model.challenge.AchievedChallenge
import com.barryburgle.gameapp.model.challenge.Challenge
import com.barryburgle.gameapp.model.date.Date
import com.barryburgle.gameapp.model.enums.ChallengeSortType
import com.barryburgle.gameapp.model.enums.DateSortType
import com.barryburgle.gameapp.model.enums.GameEventSortType
import com.barryburgle.gameapp.model.enums.SessionSortType
import com.barryburgle.gameapp.model.enums.SetSortType
import com.barryburgle.gameapp.model.game.SortableGameEvent
import com.barryburgle.gameapp.model.lead.Lead
import com.barryburgle.gameapp.model.session.AbstractSession
import com.barryburgle.gameapp.model.set.SingleSet
import com.barryburgle.gameapp.model.setting.Setting
import com.barryburgle.gameapp.model.stat.AggregatedDates
import com.barryburgle.gameapp.model.stat.AggregatedSessions
import com.barryburgle.gameapp.model.stat.CategoryHistogram
import com.barryburgle.gameapp.ui.state.ExportState

data class InputState(
    override var allSessions: List<AbstractSession> = emptyList(),
    override var allLeads: List<Lead> = emptyList(),
    var showSessions: Boolean = true,
    var showSets: Boolean = true,
    var showDates: Boolean = true,
    var showChallenges: Boolean = true,
    var date: String = "",
    var startHour: String = "",
    var endHour: String = "",
    var sets: String = "",
    var convos: String = "",
    var contacts: String = "",
    var stickingPoints: String = "",
    val sessionSortType: SessionSortType = SessionSortType.DATE,
    val dateSortType: DateSortType = DateSortType.DATE,
    val setSortType: SetSortType = SetSortType.DATE,
    val challengeSortType: ChallengeSortType = ChallengeSortType.END_DATE,
    val gameEventSortType: GameEventSortType = GameEventSortType.DATE,
    val isAddingSession: Boolean = false,
    val isAddingLiveSession: Boolean = false,
    val isUpdatingSession: Boolean = false,
    val isAddingDate: Boolean = false,
    val isUpdatingDate: Boolean = false, // TODO: after removing the setUpdateState method from dialogs consider removing the update flags like this if serve no purpose
    val isAddingSet: Boolean = false,
    val isUpdatingSet: Boolean = false,
    val isAddingLead: Boolean = false,
    val isModifyingLead: Boolean = false,
    val isUpdatingLead: Boolean = false,
    val isAddingChallenge: Boolean = false,
    val isUpdatingChallenge: Boolean = false,
    var leads: List<Lead> = emptyList(),
    var leadId: Long = 0L,
    val leadInsertTime: String = "",
    val leadSessionId: Long? = 0L,
    val leadName: String = "",
    val leadContact: String = "",
    val leadNationality: String = "",
    val leadAge: Long = 20,
    val leadContactLookupKey: String? = null,
    val leadInstagramUrl: String? = null,
    val countrySearch: String = "",
    val countryName: String = "",
    val notificationTime: String = "",
    val editAbstractSession: AbstractSession? = null,
    override var exportSessionsFileName: String = "",
    override var exportLeadsFileName: String = "",
    override var exportDatesFileName: String = "",
    override var exportSetsFileName: String = "",
    override var exportChallengesFileName: String = "",
    override var exportFolder: String = "",
    override var backupFolder: String = "",
    override var allDates: List<Date> = emptyList(),
    var allEvents: List<SortableGameEvent> = emptyList(),
    override var allSets: List<SingleSet> = emptyList(),
    override var allChallenges: List<AchievedChallenge> = emptyList(),
    override var allSettings: List<Setting> = emptyList(),
    override var backupActive: Boolean = true,
    override var lastBackup: Int = 3,
    override var justSaved: Boolean = false,
    var location: String = "",
    var dateNumber: String = "0",
    var dateType: String = "",
    var cost: String = "0",
    var tweetUrl: String = "",
    var pull: Boolean = false,
    var bounce: Boolean = false,
    var kiss: Boolean = false,
    var lay: Boolean = false,
    var recorded: Boolean = false,
    val editDate: Date? = null,
    val editSet: SingleSet? = null,
    val lead: Lead? = null,
    var conversation: Boolean = false,
    var contact: Boolean = false,
    var instantDate: Boolean = false,
    var sessionId: Long? = 0L,
    var dateId: Long? = 0L,
    override var generateiDate: Boolean = true,
    var followCount: Boolean = false,
    var suggestLeadsNationality: Boolean = true,
    val incrementChallengeGoal: Int = 5,
    val defaultChallengeGoal: Int = 20,
    var shownNationalities: Int = 6,
    var simplePlusOneReport: Boolean = true,
    var neverShareLeadInfo: Boolean = false,
    var copyReportOnClipboard: Boolean = true,
    var showCurrentWeekSummary: Boolean = false,
    var showCurrentMonthSummary: Boolean = false,
    var showCurrentChallengeSummary: Boolean = false,
    var theme: String = "",
    val mostPopularLeadsNationalities: List<CategoryHistogram> = emptyList(),
    val sessionsByWeek: List<AggregatedSessions> = emptyList(),
    val sessionsByMonth: List<AggregatedSessions> = emptyList(),
    val datesByWeek: List<AggregatedDates> = emptyList(),
    val datesByMonth: List<AggregatedDates> = emptyList(),
    var isInOverlay: Boolean = false,
    var challengeName: String = "",
    var challengeDescription: String = "",
    var challengeStartDate: String = "",
    var challengeDuration: String = "1",
    var challengeType: String = "",
    var challengeGoal: String = "20",
    var challengeTweetUrl: String = "",
    val editChallenge: Challenge? = null,
    var saveLeadToLiveSession: Boolean = false,
) : ExportState(
    sessionSortType,
    exportSessionsFileName,
    exportLeadsFileName,
    exportDatesFileName,
    exportSetsFileName,
    exportChallengesFileName,
    "",// Not passing a valid exportSettingFileName because it is not used from InputScreen features for any settings export
    exportFolder,
    backupFolder,
    allSessions,
    allLeads,
    allDates,
    allSets,
    allChallenges,
    allSettings,
    backupActive,
    lastBackup,
    justSaved
)
