package com.barryburgle.gameapp.ui.tool.state

import com.barryburgle.gameapp.model.challenge.AchievedChallenge
import com.barryburgle.gameapp.model.date.Date
import com.barryburgle.gameapp.model.enums.ThemeEnum
import com.barryburgle.gameapp.model.lead.Lead
import com.barryburgle.gameapp.model.session.AbstractSession
import com.barryburgle.gameapp.model.set.SingleSet
import com.barryburgle.gameapp.model.setting.Setting
import com.barryburgle.gameapp.ui.state.ExportState

data class ToolsState(
    override var exportSessionsFileName: String = "",
    var importSessionsFileName: String = "",
    override var exportLeadsFileName: String = "",
    var importLeadsFileName: String = "",
    override var exportDatesFileName: String = "",
    var importDatesFileName: String = "",
    override var exportSetsFileName: String = "",
    var importSetsFileName: String = "",
    override var exportChallengesFileName: String = "",
    var importChallengesFileName: String = "",
    override var exportSettingsFileName: String = "",
    var importSettingsFileName: String = "",
    override var exportFolder: String = "",
    var importFolder: String = "",
    override var backupFolder: String = "",
    override var allSessions: List<AbstractSession> = emptyList(),
    override var allLeads: List<Lead> = emptyList(),
    override var allDates: List<Date> = emptyList(),
    override var allSets: List<SingleSet> = emptyList(),
    override var allChallenges: List<AchievedChallenge> = emptyList(),
    override var allSettings: List<Setting> = emptyList(),
    val lastSessionAverageQuantity: Int = 4,
    val lastSessionsShown: Int = 14,
    val lastWeeksShown: Int = 8,
    val lastMonthsShown: Int = 4,
    val notificationTime: String = "",
    var exportHeader: Boolean = true,
    var importHeader: Boolean = true,
    override var backupActive: Boolean = true,
    override var lastBackup: Int = 3,
    val latestAvailable: String = "",
    val latestPublishDate: String = "",
    val latestChangelog: String = "",
    val latestDownloadUrl: String = "",
    val showChangelog: Boolean = false,
    var backupBeforeUpdate: Boolean = true,
    override var generateiDate: Boolean = true,
    var followCount: Boolean = false,
    var suggestLeadsNationality: Boolean = true,
    val shownNationalities: Int = 6,
    var archiveBackupFolder: Boolean = true,
    var deleteSessions: Boolean = false,
    var deleteLeads: Boolean = false,
    var deleteDates: Boolean = false,
    var deleteSets: Boolean = false,
    var deleteChallenges: Boolean = false,
    var deleteSettings: Boolean = false,
    var isCleaning: Boolean = false,
    var themeSysFollow: Boolean = false,
    var simplePlusOneReport: Boolean = true,
    var neverShareLeadInfo: Boolean = false,
    var copyReportOnClipboard: Boolean = true,
    var showCurrentWeekSummary: Boolean = false,
    var showCurrentMonthSummary: Boolean = false,
    var showCurrentChallengeSummary: Boolean = false,
    val incrementChallengeGoal: Int = 5,
    val defaultChallengeGoal: Int = 20,
    var theme: String = ThemeEnum.LIGHT.type,
    var deleteConfirmationPrompt: String = "",
    override var liveSessionNotificationEnabled: Boolean = true,
    override var liveSessionSittingReminderEnabled: Boolean = true,
    override var liveSessionSittingReminderInterval: Int = 30,
    override var liveSessionShareEnabled: Boolean = true
) : ExportState(
    null,
    exportSessionsFileName,
    exportLeadsFileName,
    exportDatesFileName,
    exportSetsFileName,
    exportChallengesFileName,
    exportSettingsFileName,
    exportFolder,
    backupFolder,
    allSessions,
    allLeads,
    allDates,
    allSets,
    allChallenges,
    allSettings,
    backupActive,
    lastBackup
)
