package com.barryburgle.gameapp.model.enums

enum class RecordingActionEnum(val action: String) {
    START_RECORDING("ACTION_START_RECORDING"),
    STOP_RECORDING("ACTION_STOP_RECORDING"),
    DISCARD_RECORDING("ACTION_DISCARD_RECORDING"),
    START_PLAYBACK("ACTION_START_PLAYBACK"),
    PAUSE_PLAYBACK("ACTION_PAUSE_PLAYBACK"),
    STOP_PLAYBACK("ACTION_STOP_PLAYBACK"),
    SEEK_PLAYBACK("ACTION_SEEK_PLAYBACK")
}